---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

#- name: Install Kibana.
#  package:
#    name: "{{ kibana_package }}"
#    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name:  install logtrail in kibana
  shell: /usr/share/kibana/bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.29/logtrail-6.3.2-0.1.29.zip
  notify: restart kibana
